apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flagger
  namespace: appmesh-system
spec:
  releaseName: flagger
  chart:
    repository: https://flagger.app
    name: flagger
    version: 0.20.3
  values:
    image:
      repository: weaveworks/flagger
      tag: 0.20.3
    crd:
      create: false
    metricsServer: http://appmesh-prometheus:9090
    meshProvider: appmesh
